export const EMPLOYEES_LOADED = 'EMPLOYEES_LOADED';
export const EMPLOYEE_ADD = 'EMPLOYEE_ADD';
export const EMPLOYEE_CHANGE = 'EMPLOYEE_CHANGE';
export const EMPLOYEE_REMOVE = 'EMPLOYEE_REMOVE';
export const FORM_FIELD_CHANGE = 'FORM_FIELD_CHANGE';
export const FORM_FIELD_VALIDATE = 'FORM_FIELD_VALIDATE';
export const FORM_RESET = 'FORM_RESET';
export const EDITOR_SWITCH = 'EDITOR_SWITCH';
